sudo: required

language: generic

services: docker

before_script:
  - echo "start creating  an image with Dockerfile"
  - cd ./src/react-for-docker/
  - docker build -t jordy-react-image -f Dockerfile.dev ./

script:
  - docker run -e CI=true jordy-react-image npm run test -- --coverage

after_success:
  - echo "Test success!!"

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "jordy-docker-react"
  env: "Jordydockerreact-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-777582115357
  bucket_path: jordy-docker-react
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY